const translations = {
    "zh-CN": {
        "description": "中国高品质紧固件制造商，提供螺栓、螺钉、铆钉及定制紧固件。",
        "keywords": "紧固件, 螺栓, 螺钉, 铆钉, 定制紧固件, 制造商",
        "author": "厦门小小螺丝有限公司",
        "title": "紧固件制造商 | 高品质螺栓与螺钉 | 厦门小小螺丝有限公司",
        "name_top": "厦门小小螺丝有限公司",
        "nav_about": "关于公司",
        "nav_categories": "产品分类",
        "nav_products": "我们产品",
        "nav_contact": "联系我们",
        "hero_title": "小小螺丝钉 祝您事业兴",
        "hero_subtitle": "您值得信赖的螺栓、螺钉、铆钉及定制零件合作伙伴",
        "about_title": "关于我们",
        "about_text": "厦门小小螺丝有限公司于1993年在福建省厦门市集美区金辉路投资兴办，是一家专业从事紧固件研发、生产与销售的企业。我们致力于为全球客户提供最优质的螺栓、螺钉、铆钉及定制紧固件解决方案，以卓越的品质和服务赢得客户信赖。",
        "categories_text": "我们提供多种类型的紧固件，适用于不同行业和需求。无论是标准件还是定制件，我们都能为您提供最佳解决方案。",
        "nav_car": "汽配类",
        "nav_bath": "卫浴类",
        "nav_sports": "运动器材类",
        "nav_furniture": "家具类",
        "nav_electronics": "电子电器类",
        "nav_machinery": "车床类",
        "our-products": "产品中心",
        "our-products_nav1": "螺钉",
        "our-products_nav2": "螺栓",
        "our-products_nav3": "螺丝",
        "our-products_nav4": "螺母",
        "our-products_nav5": "垫圈",
        "our-products_nav6": "别针",
        "our-products_nav7": "组合件",
        "our-products_nav8": "定制品",
        "why_choose_us": "为什么选择我们",
        "why1_title": "工厂实力",
        "why1_description": "自有厂房，集研发、生产、销售为一体的专业紧固件制造商。",
        "why2_title": "行业经验",
        "why2_description": "30多年行业经验，采用高品质的材料和制造工艺，深耕市场。",
        "why3_title": "价格优势",
        "why3_description": "具有竞争力的定价，会是您在紧固件行业中最佳的选择。",
        "equipment_title": "生产设备",
        "equipment_text": "我们拥有先进的生产设备，确保高效、高质量的生产能力。",
        "nav_equipment1": "生产设备 1",
        "nav_equipment2": "生产设备 2",
        "nav_equipment3": "生产设备 3",
        "nav_equipment4": "生产设备 4",
        "office_title": "办公环境",
        "office_text": "我们拥有现代化的办公环境，致力于为员工提供一个舒适和高效的工作空间。",
        "nav_office1": "办公环境 1",
        "nav_office2": "办公环境 2",
        "nav_office3": "办公环境 3",
        "nav_office4": "办公环境 4",
        "contact_us": "联系我们",
        "contact_us2": "联系方式",
        "contact_email": "邮箱：junchen@xiaoxiaoluosi.com",
        "contact_address_title": "公司地址",
        "contact_name": "厦门小小螺丝有限公司",
        "contact_address": "地址：福建省厦门市集美区后溪金辉路24号小小螺丝有限公司",
        "contact_wechat": "微信：Jins76699",
        "contact_whatsapp": "WhatsApp：+62 858 2975 3752",
        "copyright": "&copy; 2025 厦门小小螺丝有限公司. 版权所有.",
        "map": "正在加载地图...",
        "car1": "汽配螺丝1", "car2": "汽配螺丝2", "car3": "汽配螺丝3", "car4": "汽配螺丝4",
        "car5": "汽配螺丝5", "car6": "汽配螺丝6", "car7": "汽配螺丝7", "car8": "汽配螺丝8",
        "bathroom1": "卫浴螺丝1", "bathroom2": "卫浴螺丝2", "bathroom3": "卫浴螺丝3", "bathroom4": "卫浴螺丝4",
        "bathroom5": "卫浴螺丝5", "bathroom6": "卫浴螺丝6", "bathroom7": "卫浴螺丝7", "bathroom8": "卫浴螺丝8",
        "sports1": "运动器材螺丝1", "sports2": "运动器材螺丝2", "sports3": "运动器材螺丝3", "sports4": "运动器材螺丝4",
        "sports5": "运动器材螺丝5", "sports6": "运动器材螺丝6", "sports7": "运动器材螺丝7", "sports8": "运动器材螺丝8",
        "furniture1": "家具螺丝1", "furniture2": "家具螺丝2", "furniture3": "家具螺丝3", "furniture4": "家具螺丝4",
        "furniture5": "家具螺丝5", "furniture6": "家具螺丝6", "furniture7": "家具螺丝7", "furniture8": "家具螺丝8",
        "electronics1": "电子螺丝1", "electronics2": "电子螺丝2", "electronics3": "电子螺丝3", "electronics4": "电子螺丝4",
        "electronics5": "电子螺丝5", "electronics6": "电子螺丝6", "electronics7": "电子螺丝7", "electronics8": "电子螺丝8",
        "machinery1": "车床螺丝1", "machinery2": "车床螺丝2", "machinery3": "车床螺丝3", "machinery4": "车床螺丝4",
        "machinery5": "车床螺丝5", "machinery6": "车床螺丝6", "machinery7": "车床螺丝7", "machinery8": "车床螺丝8",
    },
    "zh-TW": {
        "description": "中國高品質緊固件製造商，提供螺栓、螺釘、鉚釘及定制緊固件。",
        "keywords": "緊固件, 螺栓, 螺釘, 鉚釘, 定制緊固件, 製造商",
        "author": "廈門小小螺絲有限公司",
        "title": "緊固件製造商 | 高品質螺栓與螺釘 | 廈門小小螺絲有限公司",
        "name_top": "廈門小小螺絲有限公司",
        "nav_home": "首頁",
        "nav_about": "關於公司",
        "nav_categories": "產品分類",
        "nav_products": "我們產品",
        "nav_contact": "聯繫我們",
        "hero_title": "小小螺絲釘 祝您事業興",
        "hero_subtitle": "您值得信賴的螺栓、螺釘、鉚釘及定制零件合作夥伴",
        "about_title": "關於我們",
        "about_text": "廈門小小螺絲有限公司於1993年在福建省廈門市集美區金輝路投資興辦，是一家專業從事緊固件研發、生產與銷售的企業。我們致力於為全球客戶提供最優質的螺栓、螺釘、鉚釘及定制緊固件解決方案，以卓越的品質和服務贏得客戶信賴。",
        "categories_text": "我們提供多種類型的緊固件，適用於不同行業和需求。無論是標準件還是定制件，我們都能為您提供最佳解決方案。",
        "nav_car": "汽配類",
        "nav_bath": "衛浴類",
        "nav_sports": "運動器材類",
        "nav_furniture": "家具類",
        "nav_electronics": "電子電器類",
        "nav_machinery": "車床類",
        "our-products": "產品中心",
        "our-products_nav1": "螺釘",
        "our-products_nav2": "螺栓",
        "our-products_nav3": "螺絲",
        "our-products_nav4": "螺母",
        "our-products_nav5": "墊圈",
        "our-products_nav6": "別針",
        "our-products_nav7": "組合件",
        "our-products_nav8": "定製品",
        "why_choose_us": "為什麼選擇我們",
        "why1_title": "工廠實力",
        "why1_description": "自有廠房，集研發、生產、銷售為一體的專業緊固件製造商。",
        "why2_title": "行業經驗",
        "why2_description": "30多年行業經驗，採用高品質的材料和製造工藝，深耕市場。",
        "why3_title": "價格優勢",
        "why3_description": "具有競爭力的定價，會是您在緊固件行業中最佳的選擇。",
        "equipment_title": "生產設備",
        "equipment_text": "我們擁有先進的生產設備，確保高效、高質量的生產能力。",
        "nav_equipment1": "生產設備 1",
        "nav_equipment2": "生產設備 2",
        "nav_equipment3": "生產設備 3",
        "nav_equipment4": "生產設備 4",
        "office_title": "辦公環境",
        "office_text": "我們擁有現代化的辦公環境，致力於為員工提供一個舒適和高效的工作空間。",
        "nav_office1": "辦公環境 1",
        "nav_office2": "辦公環境 2",
        "nav_office3": "辦公環境 3",
        "nav_office4": "辦公環境 4",
        "contact_us": "聯繫我們",
        "contact_us2": "聯繫方式",
        "contact_email": "郵箱：junchen@xiaoxiaoluosi.com",
        "contact_address_title": "公司地址",
        "contact_name": "廈門小小螺絲有限公司",
        "contact_address": "地址：福建省廈門市集美區後溪金輝路24號小小螺絲有限公司",
        "contact_wechat": "微信：Jins76699",
        "contact_whatsapp": "WhatsApp：+62 858 2975 3752",
        "copyright": "&copy; 2025 廈門小小螺絲有限公司. 版權所有.",
        "map": "正在加載地圖...",
        "car1": "汽配螺絲1", "car2": "汽配螺絲2", "car3": "汽配螺絲3", "car4": "汽配螺絲4",
        "car5": "汽配螺絲5", "car6": "汽配螺絲6", "car7": "汽配螺絲7", "car8": "汽配螺絲8",
        "bathroom1": "衛浴螺絲1", "bathroom2": "衛浴螺絲2", "bathroom3": "衛浴螺絲3", "bathroom4": "衛浴螺絲4",
        "bathroom5": "衛浴螺絲5", "bathroom6": "衛浴螺絲6", "bathroom7": "衛浴螺絲7", "bathroom8": "衛浴螺絲8",
        "sports1": "運動器材螺絲1", "sports2": "運動器材螺絲2", "sports3": "運動器材螺絲3", "sports4": "運動器材螺絲4",
        "sports5": "運動器材螺絲5", "sports6": "運動器材螺絲6", "sports7": "運動器材螺絲7", "sports8": "運動器材螺絲8",
        "furniture1": "家具螺絲1", "furniture2": "家具螺絲2", "furniture3": "家具螺絲3", "furniture4": "家具螺絲4",
        "furniture5": "家具螺絲5", "furniture6": "家具螺絲6", "furniture7": "家具螺絲7", "furniture8": "家具螺絲8",
        "electronics1": "電子螺絲1", "electronics2": "電子螺絲2", "electronics3": "電子螺絲3", "electronics4": "電子螺絲4",
        "electronics5": "電子螺絲5", "electronics6": "電子螺絲6", "electronics7": "電子螺絲7", "electronics8": "電子螺絲8",
        "machinery1": "車床螺絲1", "machinery2": "車床螺絲2", "machinery3": "車床螺絲3", "machinery4": "車床螺絲4",
        "machinery5": "車床螺絲5", "machinery6": "車床螺絲6", "machinery7": "車床螺絲7", "machinery8": "車床螺絲8",
    },
    "en": {
        "description": "High-quality fastener manufacturer in China, providing bolts, screws, rivets, and custom fasteners.",
        "keywords": "fasteners, bolts, screws, rivets, custom fasteners, manufacturer",
        "author": "Xiamen Xiaoxiao Screw Co., Ltd.",
        "title": "Fastener Manufacturer | High-Quality Bolts & Screws | Xiamen Xiaoxiao Screw Co., Ltd.",
        "name_top": "厦门小小螺丝有限公司",
        "nav_home": "Home",
        "nav_about": "About Us",
        "nav_categories": "Categories",
        "nav_products": "Products",
        "nav_contact": "Contact",
        "hero_title": "Xiaoxiao Screws, Helping Your Business Grow",
        "hero_subtitle": "Your Trusted Partner for Bolts, Screws, Rivets, and Custom Fasteners",
        "about_title": "About Us",
        "about_text": "Xiamen Xiaoxiao Screw Co., Ltd. was established in 1993 in Jimei District, Xiamen, Fujian Province. It is a professional company engaged in the research, development, production, and sales of fasteners. We are committed to providing global customers with high-quality bolts, screws, rivets, and customized fastener solutions, winning their trust with excellent quality and service.",
        "categories_text": "We offer a variety of fasteners suitable for different industries and needs. Whether standard or custom parts, we provide the best solutions for you.",
        "nav_car": "car",
        "nav_bath": "bathroom",
        "nav_sports": "sports",
        "nav_furniture": "furniture",
        "nav_electronics": "electronics",
        "nav_machinery": "machinery",
        "our-products": "Product Center",
        "our-products_nav1": "Screw",
        "our-products_nav2": "Bolt",
        "our-products_nav3": "Screw (General)",
        "our-products_nav4": "Nut",
        "our-products_nav5": "Washer",
        "our-products_nav6": "Pin",
        "our-products_nav7": "Assembly Parts",
        "our-products_nav8": "Custom Parts",
        "why_choose_us": "Why Choose Us",
        "why1_title": "Factory Strength",
        "why1_description": "Own factory, integrating R&D, production, and sales as a professional fastener manufacturer.",
        "why2_title": "Industry Experience",
        "why2_description": "Over 30 years of industry experience, using high-quality materials and manufacturing processes to serve the market.",
        "why3_title": "Competitive Pricing",
        "why3_description": "Competitive pricing makes us the best choice in the fastener industry.",
        "equipment_title": "Production Equipment",
        "equipment_text": "We have advanced production equipment to ensure efficient and high-quality manufacturing capabilities.",
        "nav_equipment1": "Production Equipment 1",
        "nav_equipment2": "Production Equipment 2",
        "nav_equipment3": "Production Equipment 3",
        "nav_equipment4": "Production Equipment 4",
        "office_title": "Office Environment",
        "office_text": "We have a modern office environment dedicated to providing employees with a comfortable and efficient workspace.",
        "nav_office1": "Office Environment 1",
        "nav_office2": "Office Environment 2",
        "nav_office3": "Office Environment 3",
        "nav_office4": "Office Environment 4",
        "contact_us": "Contact Us",
        "contact_us2": "Contact information",
        "contact_email": "Email：junchen@xiaoxiaoluosi.com",
        "contact_address_title": "Company Address",
        "contact_name": "Xiamen Xiaoxiao Screw Co., Ltd.",
        "contact_address": "Address: No. 24, Jinhui Road, Houxi, Jimei District, Xiamen, Fujian, China",
        "contact_wechat": "WeChat: Jins76699",
        "contact_whatsapp": "WhatsApp: +62 858 2975 3752",
        "copyright": "&copy; 2025 Xiamen Xiaoxiao Screw Co., Ltd. All rights reserved.",
        "map": "Loading map...",
        "car1": "Auto Screw 1", "car2": "Auto Screw 2", "car3": "Auto Screw 3", "car4": "Auto Screw 4",
        "car5": "Auto Screw 5", "car6": "Auto Screw 6", "car7": "Auto Screw 7", "car8": "Auto Screw 8",
        "bathroom1": "Bathroom Screw 1", "bathroom2": "Bathroom Screw 2", "bathroom3": "Bathroom Screw 3", "bathroom4": "Bathroom Screw 4",
        "bathroom5": "Bathroom Screw 5", "bathroom6": "Bathroom Screw 6", "bathroom7": "Bathroom Screw 7", "bathroom8": "Bathroom Screw 8",
        "sports1": "Sports Screw 1", "sports2": "Sports Screw 2", "sports3": "Sports Screw 3", "sports4": "Sports Screw 4",
        "sports5": "Sports Screw 5", "sports6": "Sports Screw 6", "sports7": "Sports Screw 7", "sports8": "Sports Screw 8",
        "furniture1": "Furniture Screw 1", "furniture2": "Furniture Screw 2", "furniture3": "Furniture Screw 3", "furniture4": "Furniture Screw 4",
        "furniture5": "Furniture Screw 5", "furniture6": "Furniture Screw 6", "furniture7": "Furniture Screw 7", "furniture8": "Furniture Screw 8",
        "electronics1": "Electronics Screw 1", "electronics2": "Electronics Screw 2", "electronics3": "Electronics Screw 3", "electronics4": "Electronics Screw 4",
        "electronics5": "Electronics Screw 5", "electronics6": "Electronics Screw 6", "electronics7": "Electronics Screw 7", "electronics8": "Electronics Screw 8",
        "machinery1": "Machinery Screw 1", "machinery2": "Machinery Screw 2", "machinery3": "Machinery Screw 3", "machinery4": "Machinery Screw 4",
        "machinery5": "Machinery Screw 5", "machinery6": "Machinery Screw 6", "machinery7": "Machinery Screw 7", "machinery8": "Machinery Screw 8",
    },
       "fr": {
    "description": "Fabricant chinois de fixations de haute qualité, fournissant des boulons, des vis, des rivets et des fixations sur mesure.",
    "keywords": "fixations, boulons, vis, rivets, fixations sur mesure, fabricant",
    "author": "Xiamen Xiaoxiao Screw Co., Ltd.",
    "title": "Fabricant de Fixations | Boulons et Vis de Haute Qualité | Xiamen Xiaoxiao Screw Co., Ltd.",
    "name_top": "厦门小小螺丝有限公司",
    "nav_about": "À propos de nous",
    "nav_categories": "Catégories de produits",
    "nav_products": "Nos produits",
    "nav_contact": "Nous contacter",
    "hero_title": "Petites vis, grand succès pour votre entreprise",
    "hero_subtitle": "Votre partenaire de confiance pour les boulons, les vis, les rivets et les fixations sur mesure",
    "about_title": "À propos de nous",
    "about_text": "Xiamen Xiaoxiao Screw Co., Ltd. a été fondée en 1993 dans le district de Jimei, à Xiamen, dans la province du Fujian. Nous sommes une entreprise spécialisée dans la recherche, le développement, la production et la vente de fixations. Nous nous engageons à fournir à nos clients du monde entier des boulons, des vis, des rivets et des solutions de fixation sur mesure de haute qualité, en gagnant leur confiance grâce à une qualité et un service exceptionnels.",
    "categories_text": "Nous proposons une variété de fixations adaptées aux différents secteurs et besoins. Qu'il s'agisse de pièces standard ou sur mesure, nous vous offrons la meilleure solution.",
    "nav_car": "Pièces automobiles",
    "nav_bath": "Sanitaire",
    "nav_sports": "Équipement sportif",
    "nav_furniture": "Meubles",
    "nav_electronics": "Électronique",
    "nav_machinery": "Machines",
    "our-products": "Centre de produits",
    "our-products_nav1": "Vis",
    "our-products_nav2": "Boulons",
    "our-products_nav3": "Vis filetées",
    "our-products_nav4": "Écrous",
    "our-products_nav5": "Rondelles",
    "our-products_nav6": "Goupilles",
    "our-products_nav7": "Assemblages",
    "our-products_nav8": "Produits sur mesure",
    "why_choose_us": "Pourquoi nous choisir ?",
    "why1_title": "Capacités de fabrication",
    "why1_description": "Usine propre, intégrant la R&D, la production et la vente en tant que fabricant professionnel de fixations.",
    "why2_title": "Expérience du secteur",
    "why2_description": "Plus de 30 ans d'expérience dans le secteur, utilisant des matériaux de haute qualité et des procédés de fabrication avancés.",
    "why3_title": "Prix compétitif",
    "why3_description": "Des prix compétitifs font de nous le meilleur choix dans l'industrie des fixations.",
    "equipment_title": "Équipements de production",
    "equipment_text": "Nous disposons d'équipements de production avancés garantissant une production efficace et de haute qualité.",
    "nav_equipment1": "Équipement de production 1",
    "nav_equipment2": "Équipement de production 2",
    "nav_equipment3": "Équipement de production 3",
    "nav_equipment4": "Équipement de production 4",
    "office_title": "Environnement de bureau",
    "office_text": "Nous disposons d'un environnement de bureau moderne, offrant un espace de travail confortable et efficace pour nos employés.",
    "nav_office1": "Bureau 1",
    "nav_office2": "Bureau 2",
    "nav_office3": "Bureau 3",
    "nav_office4": "Bureau 4",
    "contact_us": "Nous contacter",
    "contact_us2": "Informations de contact",
    "contact_email": "E-mail：junchen@xiaoxiaoluosi.com",
    "contact_address_title": "Adresse de l'entreprise",
    "contact_name": "Xiamen Xiaoxiao Screw Co., Ltd.",
    "contact_address": "24, route Jinhui, Houxi, Jimei, Xiamen, Fujian, Chine",
    "contact_wechat": "WeChat: Jins76699",
    "contact_whatsapp": "WhatsApp: +62 858 2975 3752",
    "copyright": "&copy; 2025 Xiamen Xiaoxiao Screw Co., Ltd. Tous droits réservés.",
    "map": "Chargement de la carte...",
    "car1": "Vis automobile 1", "car2": "Vis automobile 2", "car3": "Vis automobile 3", "car4": "Vis automobile 4",
    "car5": "Vis automobile 5", "car6": "Vis automobile 6", "car7": "Vis automobile 7", "car8": "Vis automobile 8",
    "bathroom1": "Vis sanitaire 1", "bathroom2": "Vis sanitaire 2", "bathroom3": "Vis sanitaire 3", "bathroom4": "Vis sanitaire 4",
    "bathroom5": "Vis sanitaire 5", "bathroom6": "Vis sanitaire 6", "bathroom7": "Vis sanitaire 7", "bathroom8": "Vis sanitaire 8",
    "sports1": "Vis pour équipement sportif 1", "sports2": "Vis pour équipement sportif 2", "sports3": "Vis pour équipement sportif 3", "sports4": "Vis pour équipement sportif 4",
    "sports5": "Vis pour équipement sportif 5", "sports6": "Vis pour équipement sportif 6", "sports7": "Vis pour équipement sportif 7", "sports8": "Vis pour équipement sportif 8",
    "furniture1": "Vis pour meubles 1", "furniture2": "Vis pour meubles 2", "furniture3": "Vis pour meubles 3", "furniture4": "Vis pour meubles 4",
    "furniture5": "Vis pour meubles 5", "furniture6": "Vis pour meubles 6", "furniture7": "Vis pour meubles 7", "furniture8": "Vis pour meubles 8",
    "electronics1": "Vis électronique 1", "electronics2": "Vis électronique 2", "electronics3": "Vis électronique 3", "electronics4": "Vis électronique 4",
    "electronics5": "Vis électronique 5", "electronics6": "Vis électronique 6", "electronics7": "Vis électronique 7", "electronics8": "Vis électronique 8",
    "machinery1": "Vis de machine 1", "machinery2": "Vis de machine 2", "machinery3": "Vis de machine 3", "machinery4": "Vis de machine 4",
    "machinery5": "Vis de machine 5", "machinery6": "Vis de machine 6", "machinery7": "Vis de machine 7", "machinery8": "Vis de machine 8",
},
	"de-DE": {
    "description": "Chinesischer Hersteller von hochwertigen Verbindungselementen, bietet Schrauben, Bolzen, Nieten und kundenspezifische Verbindungselemente an.",
    "keywords": "Verbindungselemente, Bolzen, Schrauben, Nieten, kundenspezifische Verbindungselemente, Hersteller",
    "author": "Xiamen Xiaoxiao Screw Co., Ltd.",
    "title": "Hersteller von Verbindungselementen | Hochwertige Schrauben und Bolzen | Xiamen Xiaoxiao Screw Co., Ltd.",
    "name_top": "厦门小小螺丝有限公司",
    "nav_about": "Über uns",
    "nav_categories": "Produktkategorien",
    "nav_products": "Unsere Produkte",
    "nav_contact": "Kontakt",
    "hero_title": "Kleine Schraube, große Wirkung für Ihr Geschäft",
    "hero_subtitle": "Ihr vertrauenswürdiger Partner für Schrauben, Bolzen, Nieten und kundenspezifische Teile",
    "about_title": "Über uns",
    "about_text": "Xiamen Xiaoxiao Screw Co., Ltd. wurde 1993 in der Jimei-Zone der Stadt Xiamen, Provinz Fujian, gegründet. Wir sind ein Unternehmen, das sich auf die Entwicklung, Produktion und den Vertrieb von Verbindungselementen spezialisiert hat. Unser Ziel ist es, globale Kunden mit den besten Bolzen, Schrauben, Nieten und kundenspezifischen Verbindungselementen zu versorgen und durch exzellente Qualität und Service Vertrauen zu gewinnen.",
    "categories_text": "Wir bieten eine Vielzahl von Verbindungselementen für unterschiedliche Branchen und Anforderungen an. Egal ob Standard- oder Sonderanfertigungen, wir liefern Ihnen die beste Lösung.",
    "nav_car": "Automobilteile",
    "nav_bath": "Sanitärteile",
    "nav_sports": "Sportgeräte",
    "nav_furniture": "Möbelteile",
    "nav_electronics": "Elektronikteile",
    "nav_machinery": "Maschinenteile",
    "our-products": "Produktübersicht",
    "our-products_nav1": "Schrauben",
    "our-products_nav2": "Bolzen",
    "our-products_nav3": "Gewindeschrauben",
    "our-products_nav4": "Muttern",
    "our-products_nav5": "Unterlegscheiben",
    "our-products_nav6": "Stifte",
    "our-products_nav7": "Baugruppen",
    "our-products_nav8": "Maßanfertigungen",
    "why_choose_us": "Warum uns wählen?",
    "why1_title": "Fabrikkompetenz",
    "why1_description": "Eigene Produktionsstätte, professioneller Hersteller von Verbindungselementen mit Forschung, Produktion und Vertrieb.",
    "why2_title": "Branchenerfahrung",
    "why2_description": "Über 30 Jahre Erfahrung in der Branche, hochwertige Materialien und Fertigungsprozesse.",
    "why3_title": "Preisvorteil",
    "why3_description": "Wettbewerbsfähige Preise – die beste Wahl in der Verbindungselementebranche.",
    "equipment_title": "Produktionsausrüstung",
    "equipment_text": "Wir verfügen über fortschrittliche Produktionsanlagen, um eine effiziente und qualitativ hochwertige Produktion zu gewährleisten.",
    "nav_equipment1": "Produktionsmaschine 1",
    "nav_equipment2": "Produktionsmaschine 2",
    "nav_equipment3": "Produktionsmaschine 3",
    "nav_equipment4": "Produktionsmaschine 4",
    "office_title": "Büroumgebung",
    "office_text": "Wir verfügen über eine moderne Büroumgebung und sind bestrebt, unseren Mitarbeitern einen komfortablen und effizienten Arbeitsplatz zu bieten.",
    "nav_office1": "Büro 1",
    "nav_office2": "Büro 2",
    "nav_office3": "Büro 3",
    "nav_office4": "Büro 4",
    "contact_us": "Kontaktieren Sie uns",
    "contact_us2": "Kontaktinformationen",
    "contact_email": "E-Mail：junchen@xiaoxiaoluosi.com",
    "contact_address_title": "Firmenadresse",
    "contact_name": "Xiamen Xiaoxiao Screw Co., Ltd.",
    "contact_address": "Jinhui Road 24, Houxi, Jimei, Xiamen, Fujian, China",
        "contact_wechat": "WeChat: Jins76699",
        "contact_whatsapp": "WhatsApp: +62 858 2975 3752",
    "copyright": "&copy; 2025 Xiamen Xiaoxiao Screw Co., Ltd. Alle Rechte vorbehalten.",
    "map": "Lade Karte...",
    "car1": "Automobilschraube 1", "car2": "Automobilschraube 2", "car3": "Automobilschraube 3", "car4": "Automobilschraube 4",
    "car5": "Automobilschraube 5", "car6": "Automobilschraube 6", "car7": "Automobilschraube 7", "car8": "Automobilschraube 8",
    "bathroom1": "Sanitärschraube 1", "bathroom2": "Sanitärschraube 2", "bathroom3": "Sanitärschraube 3", "bathroom4": "Sanitärschraube 4",
    "bathroom5": "Sanitärschraube 5", "bathroom6": "Sanitärschraube 6", "bathroom7": "Sanitärschraube 7", "bathroom8": "Sanitärschraube 8",
    "sports1": "Sportgeräteschraube 1", "sports2": "Sportgeräteschraube 2", "sports3": "Sportgeräteschraube 3", "sports4": "Sportgeräteschraube 4",
    "sports5": "Sportgeräteschraube 5", "sports6": "Sportgeräteschraube 6", "sports7": "Sportgeräteschraube 7", "sports8": "Sportgeräteschraube 8",
    "furniture1": "Möbelschraube 1", "furniture2": "Möbelschraube 2", "furniture3": "Möbelschraube 3", "furniture4": "Möbelschraube 4",
    "furniture5": "Möbelschraube 5", "furniture6": "Möbelschraube 6", "furniture7": "Möbelschraube 7", "furniture8": "Möbelschraube 8",
    "electronics1": "Elektronikschraube 1", "electronics2": "Elektronikschraube 2", "electronics3": "Elektronikschraube 3", "electronics4": "Elektronikschraube 4",
    "electronics5": "Elektronikschraube 5", "electronics6": "Elektronikschraube 6", "electronics7": "Elektronikschraube 7", "electronics8": "Elektronikschraube 8",
    "machinery1": "Maschinenschraube 1", "machinery2": "Maschinenschraube 2", "machinery3": "Maschinenschraube 3", "machinery4": "Maschinenschraube 4",
    "machinery5": "Maschinenschraube 5", "machinery6": "Maschinenschraube 6", "machinery7": "Maschinenschraube 7", "machinery8": "Maschinenschraube 8",
},
	"ru": {
    "description": "Китайский производитель высококачественного крепежа, предлагающий болты, винты, заклепки и нестандартные крепежные изделия.",
    "keywords": "крепеж, болты, винты, заклепки, нестандартный крепеж, производитель",
    "author": "Xiamen Xiaoxiao Screw Co., Ltd.",
    "title": "Производитель крепежа | Высококачественные болты и винты | Xiamen Xiaoxiao Screw Co., Ltd.",
    "name_top": "厦门小小螺丝有限公司",
    "nav_about": "О компании",
    "nav_categories": "Категории продукции",
    "nav_products": "Наши продукты",
    "nav_contact": "Контакты",
    "hero_title": "Маленький винт, большие возможности для вашего бизнеса",
    "hero_subtitle": "Ваш надежный партнер по болтам, винтам, заклепкам и нестандартным деталям",
    "about_title": "О нас",
    "about_text": "Компания Xiamen Xiaoxiao Screw Co., Ltd. была основана в 1993 году в районе Цзимэй города Сямэнь, провинция Фуцзянь. Это профессиональное предприятие, занимающееся разработкой, производством и продажей крепежных изделий. Мы стремимся предоставлять клиентам по всему миру высококачественные болты, винты, заклепки и индивидуальные крепежные решения, завоевывая доверие за счет превосходного качества и сервиса.",
    "categories_text": "Мы предлагаем широкий ассортимент крепежных изделий для различных отраслей промышленности. Будь то стандартные или нестандартные детали, мы предложим вам лучшее решение.",
    "nav_car": "Автомобильные детали",
    "nav_bath": "Сантехнические изделия",
    "nav_sports": "Спортивное оборудование",
    "nav_furniture": "Мебельная фурнитура",
    "nav_electronics": "Электронные компоненты",
    "nav_machinery": "Механические детали",
    "our-products": "Каталог продукции",
    "our-products_nav1": "Винты",
    "our-products_nav2": "Болты",
    "our-products_nav3": "Саморезы",
    "our-products_nav4": "Гайки",
    "our-products_nav5": "Шайбы",
    "our-products_nav6": "Штифты",
    "our-products_nav7": "Сборочные компоненты",
    "our-products_nav8": "Индивидуальные изделия",
    "why_choose_us": "Почему выбирают нас",
    "why1_title": "Производственные мощности",
    "why1_description": "Собственное производство, интеграция исследований, производства и продаж в одном месте.",
    "why2_title": "Опыт в отрасли",
    "why2_description": "Более 30 лет опыта в отрасли, использование высококачественных материалов и технологий производства.",
    "why3_title": "Конкурентоспособные цены",
    "why3_description": "Конкурентоспособные цены делают нас лучшим выбором в сфере крепежных изделий.",
    "equipment_title": "Производственное оборудование",
    "equipment_text": "Мы обладаем современным производственным оборудованием, обеспечивающим эффективность и высокое качество продукции.",
    "nav_equipment1": "Производственное оборудование 1",
    "nav_equipment2": "Производственное оборудование 2",
    "nav_equipment3": "Производственное оборудование 3",
    "nav_equipment4": "Производственное оборудование 4",
    "office_title": "Офисная среда",
    "office_text": "У нас современный офис, созданный для комфортной и продуктивной работы сотрудников.",
    "nav_office1": "Офис 1",
    "nav_office2": "Офис 2",
    "nav_office3": "Офис 3",
    "nav_office4": "Офис 4",
    "contact_us": "Свяжитесь с нами",
    "contact_us2": "Контактная информация",
    "contact_email": "Электронная почта：junchen@xiaoxiaoluosi.com",
    "contact_address_title": "Адрес компании",
    "contact_name": "Xiamen Xiaoxiao Screw Co., Ltd.",
    "contact_address": "№24, Цзиньхуй-роуд, район Хоуси, Цзимэй, Сямэнь, Фуцзянь, Китай",
    "contact_wechat": "WeChat: Jins76699",
    "contact_whatsapp": "WhatsApp: +62 858 2975 3752",
    "copyright": "&copy; 2025 Xiamen Xiaoxiao Screw Co., Ltd. Все права защищены.",
    "map": "Загрузка карты...",
    "car1": "Автомобильный винт 1", "car2": "Автомобильный винт 2", "car3": "Автомобильный винт 3", "car4": "Автомобильный винт 4",
    "car5": "Автомобильный винт 5", "car6": "Автомобильный винт 6", "car7": "Автомобильный винт 7", "car8": "Автомобильный винт 8",
    "bathroom1": "Сантехнический винт 1", "bathroom2": "Сантехнический винт 2", "bathroom3": "Сантехнический винт 3", "bathroom4": "Сантехнический винт 4",
    "bathroom5": "Сантехнический винт 5", "bathroom6": "Сантехнический винт 6", "bathroom7": "Сантехнический винт 7", "bathroom8": "Сантехнический винт 8",
    "sports1": "Спортивный винт 1", "sports2": "Спортивный винт 2", "sports3": "Спортивный винт 3", "sports4": "Спортивный винт 4",
    "sports5": "Спортивный винт 5", "sports6": "Спортивный винт 6", "sports7": "Спортивный винт 7", "sports8": "Спортивный винт 8",
    "furniture1": "Мебельный винт 1", "furniture2": "Мебельный винт 2", "furniture3": "Мебельный винт 3", "furniture4": "Мебельный винт 4",
    "furniture5": "Мебельный винт 5", "furniture6": "Мебельный винт 6", "furniture7": "Мебельный винт 7", "furniture8": "Мебельный винт 8",
    "electronics1": "Электронный винт 1", "electronics2": "Электронный винт 2", "electronics3": "Электронный винт 3", "electronics4": "Электронный винт 4",
    "electronics5": "Электронный винт 5", "electronics6": "Электронный винт 6", "electronics7": "Электронный винт 7", "electronics8": "Электронный винт 8",
    "machinery1": "Машиностроительный винт 1", "machinery2": "Машиностроительный винт 2", "machinery3": "Машиностроительный винт 3", "machinery4": "Машиностроительный винт 4",
    "machinery5": "Машиностроительный винт 5", "machinery6": "Машиностроительный винт 6", "machinery7": "Машиностроительный винт 7", "machinery8": "Машиностроительный винт 8",
},
    "ms": {
        "description": "Pengilang pengikat berkualiti tinggi di China, menyediakan bolt, skru, rivet dan pengikat tersuai.",
        "keywords": "pengikat, bolt, skru, rivet, pengikat tersuai, pengeluar",
        "author": "Xiamen Xiaoxiao Screw Co., Ltd.",
        "title": "Pengilang Pengikat | Bolt & Skru Berkualiti Tinggi | Xiamen Xiaoxiao Screw Co., Ltd.",
        "name_top": "厦门小小螺丝有限公司",
        "nav_home": "Laman Utama",
        "nav_about": "Tentang Kami",
        "nav_categories": "Kategori Produk",
        "nav_products": "Produk Kami",
        "nav_contact": "Hubungi Kami",
        "hero_title": "Xiaoxiao Skru, Membantu Perniagaan Anda Berkembang",
        "hero_subtitle": "Rakan Kongsi Dipercayai Anda untuk Bolt, Skru, Rivet, dan Pengikat Tersuai",
        "about_title": "Tentang Kami",
        "about_text": "Xiamen Xiaoxiao Screw Co., Ltd. telah ditubuhkan pada tahun 1993 di Daerah Jimei, Xiamen, Wilayah Fujian. Ia adalah sebuah syarikat profesional yang terlibat dalam penyelidikan, pembangunan, pengeluaran, dan penjualan pengikat. Kami komited untuk menyediakan pelanggan global dengan bolt, skru, rivet, dan penyelesaian pengikat tersuai berkualiti tinggi, serta memperoleh kepercayaan mereka melalui kualiti dan perkhidmatan yang cemerlang.",
        "categories_text": "Kami menawarkan pelbagai jenis pengikat yang sesuai untuk pelbagai industri dan keperluan. Sama ada bahagian standard atau tersuai, kami menyediakan penyelesaian terbaik untuk anda.",
        "nav_car": "kereta",
        "nav_bath": "Bilik air",
        "nav_sports": "Peralatan Sukan",
        "nav_furniture": "Perabot",
        "nav_electronics": "Elektronik",
        "nav_machinery": "Jentera",
        "our-products": "Pusat Produk",
        "our-products_nav1": "Skru",
        "our-products_nav2": "Bolt",
        "our-products_nav3": "Skru (Umum)",
        "our-products_nav4": "Nat",
        "our-products_nav5": "Pencuci",
        "our-products_nav6": "Pin",
        "our-products_nav7": "Bahagian Gabungan",
        "our-products_nav8": "Bahagian Tersuai",
        "why_choose_us": "Mengapa Memilih Kami",
        "why1_title": "Kekuatan Kilang",
        "why1_description": "Kilang sendiri, menggabungkan R&D, pengeluaran, dan jualan sebagai pengeluar pengikat profesional.",
        "why2_title": "Pengalaman Industri",
        "why2_description": "Lebih 30 tahun pengalaman industri, menggunakan bahan berkualiti tinggi dan proses pembuatan untuk pasaran.",
        "why3_title": "Harga Kompetitif",
        "why3_description": "Harga kompetitif menjadikan kami pilihan terbaik dalam industri pengikat.",
        "equipment_title": "Peralatan Pengeluaran",
        "equipment_text": "Kami mempunyai peralatan pengeluaran yang canggih untuk memastikan kecekapan dan keupayaan pembuatan berkualiti tinggi.",
        "nav_equipment1": "Peralatan Pengeluaran 1",
        "nav_equipment2": "Peralatan Pengeluaran 2",
        "nav_equipment3": "Peralatan Pengeluaran 3",
        "nav_equipment4": "Peralatan Pengeluaran 4",
        "office_title": "Persekitaran Pejabat",
        "office_text": "Kami mempunyai persekitaran pejabat moden yang berdedikasi untuk menyediakan ruang kerja yang selesa dan cekap kepada pekerja.",
        "nav_office1": "Persekitaran Pejabat 1",
        "nav_office2": "Persekitaran Pejabat 2",
        "nav_office3": "Persekitaran Pejabat 3",
        "nav_office4": "Persekitaran Pejabat 4",
        "contact_us": "Hubungi Kami",
        "contact_us2": "Maklumat hubungan",
        "contact_email": "E-mel：junchen@xiaoxiaoluosi.com",
        "contact_address_title": "Alamat Syarikat",
        "contact_name": "Xiamen Xiaoxiao Screw Co., Ltd.",
        "contact_address": "Alamat: No. 24, Jinhui Road, Houxi, Daerah Jimei, Xiamen, Fujian, China",
        "contact_wechat": "WeChat: Jins76699",
        "contact_whatsapp": "WhatsApp: +62 858 2975 3752",
        "copyright": "&copy; 2025 Xiamen Xiaoxiao Screw Co., Ltd. Hak cipta terpelihara.",
        "map": "Memuatkan peta...",
        "car1": "Skrup Automotif 1", "car2": "Skrup Automotif 2", "car3": "Skrup Automotif 3", "car4": "Skrup Automotif 4",
        "car5": "Skrup Automotif 5", "car6": "Skrup Automotif 6", "car7": "Skrup Automotif 7", "car8": "Skrup Automotif 8",
        "bathroom1": "Skrup Bilik Air 1", "bathroom2": "Skrup Bilik Air 2", "bathroom3": "Skrup Bilik Air 3", "bathroom4": "Skrup Bilik Air 4",
        "bathroom5": "Skrup Bilik Air 5", "bathroom6": "Skrup Bilik Air 6", "bathroom7": "Skrup Bilik Air 7", "bathroom8": "Skrup Bilik Air 8",
        "sports1": "Skrup Peralatan Sukan 1", "sports2": "Skrup Peralatan Sukan 2", "sports3": "Skrup Peralatan Sukan 3", "sports4": "Skrup Peralatan Sukan 4",
        "sports5": "Skrup Peralatan Sukan 5", "sports6": "Skrup Peralatan Sukan 6", "sports7": "Skrup Peralatan Sukan 7", "sports8": "Skrup Peralatan Sukan 8",
        "furniture1": "Skrup Perabot 1", "furniture2": "Skrup Perabot 2", "furniture3": "Skrup Perabot 3", "furniture4": "Skrup Perabot 4",
        "furniture5": "Skrup Perabot 5", "furniture6": "Skrup Perabot 6", "furniture7": "Skrup Perabot 7", "furniture8": "Skrup Perabot 8",
        "electronics1": "Skrup Elektronik 1", "electronics2": "Skrup Elektronik 2", "electronics3": "Skrup Elektronik 3", "electronics4": "Skrup Elektronik 4",
        "electronics5": "Skrup Elektronik 5", "electronics6": "Skrup Elektronik 6", "electronics7": "Skrup Elektronik 7", "electronics8": "Skrup Elektronik 8",
        "machinery1": "Skrup Mesin Bubut 1", "machinery2": "Skrup Mesin Bubut 2", "machinery3": "Skrup Mesin Bubut 3", "machinery4": "Skrup Mesin Bubut 4",
        "machinery5": "Skrup Mesin Bubut 5", "machinery6": "Skrup Mesin Bubut 6", "machinery7": "Skrup Mesin Bubut 7", "machinery8": "Skrup Mesin Bubut 8",
    },
    "id": {
    "description": "Produsen pengikat berkualitas tinggi di China, menyediakan baut, sekrup, paku keling, dan pengikat kustom.",
    "keywords": "pengikat, baut, sekrup, paku keling, pengikat kustom, produsen",
    "author": "Xiamen Xiaoxiao Screw Co., Ltd.",
    "title": "Produsen Pengikat | Baut & Sekrup Berkualitas Tinggi | Xiamen Xiaoxiao Screw Co., Ltd.",
    "name_top": "Xiamen Xiaoxiao Screw Co., Ltd.",
    "nav_about": "Tentang Kami",
    "nav_categories": "Kategori Produk",
    "nav_products": "Produk Kami",
    "nav_contact": "Hubungi Kami",
    "hero_title": "Sekrup Kecil, Bisnis Besar",
    "hero_subtitle": "Mitra Terpercaya Anda untuk Baut, Sekrup, Paku Keling, dan Pengikat Kustom",
    "about_title": "Tentang Kami",
    "about_text": "Xiamen Xiaoxiao Screw Co., Ltd. didirikan pada tahun 1993 di Distrik Jimei, Kota Xiamen, Provinsi Fujian. Perusahaan ini bergerak dalam penelitian, pengembangan, produksi, dan penjualan pengikat. Kami berkomitmen untuk menyediakan pelanggan global dengan baut, sekrup, paku keling, dan solusi pengikat kustom berkualitas tinggi serta membangun kepercayaan dengan kualitas dan layanan terbaik.",
    "categories_text": "Kami menawarkan berbagai jenis pengikat yang cocok untuk berbagai industri dan kebutuhan. Baik itu produk standar maupun kustom, kami memberikan solusi terbaik untuk Anda.",
    "nav_car": "Otomotif",
    "nav_bath": "Kamar Mandi",
    "nav_sports": "Peralatan Olahraga",
    "nav_furniture": "Perabotan",
    "nav_electronics": "Elektronik",
    "nav_machinery": "Mesin Bubut",
    "our-products": "Pusat Produk",
    "our-products_nav1": "Sekrup",
    "our-products_nav2": "Baut",
    "our-products_nav3": "Sekrup (Umum)",
    "our-products_nav4": "Mur",
    "our-products_nav5": "Ring",
    "our-products_nav6": "Pin",
    "our-products_nav7": "Komponen Rangkaian",
    "our-products_nav8": "Komponen Kustom",
    "why_choose_us": "Mengapa Memilih Kami",
    "why1_title": "Kapasitas Pabrik",
    "why1_description": "Pabrik sendiri, mencakup penelitian, produksi, dan penjualan sebagai produsen pengikat profesional.",
    "why2_title": "Pengalaman Industri",
    "why2_description": "Lebih dari 30 tahun pengalaman industri, menggunakan material berkualitas tinggi dan proses produksi terbaik.",
    "why3_title": "Harga Kompetitif",
    "why3_description": "Harga bersaing membuat kami menjadi pilihan terbaik di industri pengikat.",
    "equipment_title": "Peralatan Produksi",
    "equipment_text": "Kami memiliki peralatan produksi canggih untuk memastikan efisiensi dan kualitas produksi yang tinggi.",
    "nav_equipment1": "Peralatan Produksi 1",
    "nav_equipment2": "Peralatan Produksi 2",
    "nav_equipment3": "Peralatan Produksi 3",
    "nav_equipment4": "Peralatan Produksi 4",
    "office_title": "Lingkungan Kantor",
    "office_text": "Kami memiliki lingkungan kantor modern yang didedikasikan untuk menyediakan tempat kerja yang nyaman dan efisien bagi karyawan.",
    "nav_office1": "Lingkungan Kantor 1",
    "nav_office2": "Lingkungan Kantor 2",
    "nav_office3": "Lingkungan Kantor 3",
    "nav_office4": "Lingkungan Kantor 4",
    "contact_us": "Hubungi Kami",
    "contact_us2": "Informasi Kontak",
    "contact_email": "Email",
    "contact_address_title": "Alamat Perusahaan",
    "contact_name": "Xiamen Xiaoxiao Screw Co., Ltd.",
    "contact_address": "No. 24, Jalan Jinhui, Houxi, Distrik Jimei, Xiamen, Fujian, China",
    "contact_wechat": "WeChat",
    "contact_whatsapp": "WhatsApp",
    "copyright": "&copy; 2025 Xiamen Xiaoxiao Screw Co., Ltd. Hak cipta dilindungi.",
    "map": "Memuat peta...",
    "car1": "Sekrup Otomotif 1", "car2": "Sekrup Otomotif 2", "car3": "Sekrup Otomotif 3", "car4": "Sekrup Otomotif 4",
    "car5": "Sekrup Otomotif 5", "car6": "Sekrup Otomotif 6", "car7": "Sekrup Otomotif 7", "car8": "Sekrup Otomotif 8",
    "bathroom1": "Sekrup Kamar Mandi 1", "bathroom2": "Sekrup Kamar Mandi 2", "bathroom3": "Sekrup Kamar Mandi 3", "bathroom4": "Sekrup Kamar Mandi 4",
    "bathroom5": "Sekrup Kamar Mandi 5", "bathroom6": "Sekrup Kamar Mandi 6", "bathroom7": "Sekrup Kamar Mandi 7", "bathroom8": "Sekrup Kamar Mandi 8",
    "sports1": "Sekrup Peralatan Olahraga 1", "sports2": "Sekrup Peralatan Olahraga 2", "sports3": "Sekrup Peralatan Olahraga 3", "sports4": "Sekrup Peralatan Olahraga 4",
    "sports5": "Sekrup Peralatan Olahraga 5", "sports6": "Sekrup Peralatan Olahraga 6", "sports7": "Sekrup Peralatan Olahraga 7", "sports8": "Sekrup Peralatan Olahraga 8",
    "furniture1": "Sekrup Perabotan 1", "furniture2": "Sekrup Perabotan 2", "furniture3": "Sekrup Perabotan 3", "furniture4": "Sekrup Perabotan 4",
    "furniture5": "Sekrup Perabotan 5", "furniture6": "Sekrup Perabotan 6", "furniture7": "Sekrup Perabotan 7", "furniture8": "Sekrup Perabotan 8",
    "electronics1": "Sekrup Elektronik 1", "electronics2": "Sekrup Elektronik 2", "electronics3": "Sekrup Elektronik 3", "electronics4": "Sekrup Elektronik 4",
    "electronics5": "Sekrup Elektronik 5", "electronics6": "Sekrup Elektronik 6", "electronics7": "Sekrup Elektronik 7", "electronics8": "Sekrup Elektronik 8",
    "machinery1": "Sekrup Mesin Bubut 1", "machinery2": "Sekrup Mesin Bubut 2", "machinery3": "Sekrup Mesin Bubut 3", "machinery4": "Sekrup Mesin Bubut 4",
    "machinery5": "Sekrup Mesin Bubut 5", "machinery6": "Sekrup Mesin Bubut 6", "machinery7": "Sekrup Mesin Bubut 7", "machinery8": "Sekrup Mesin Bubut 8",
}
};

// 获取 URL 语言参数
function getLanguageFromURL() {
    const params = new URLSearchParams(window.location.search);
    return params.get("lang") || localStorage.getItem("selectedLanguage") || "zh-CN"; // 默认中文
}

// 应用语言切换
function applyLanguage(lang) {
    document.querySelectorAll("[data-i18n]").forEach(el => { 
        let key = el.getAttribute("data-i18n");
        if (translations[lang] && translations[lang][key]) {
            el.innerText = translations[lang][key];
        }
    });

    // 更新本地存储，记住用户选择
    localStorage.setItem("selectedLanguage", lang);
}

// 语言切换时调用
function setLanguage(lang) {
    // 更新 URL，但不刷新页面
    window.history.replaceState({}, "", `?lang=${lang}`);

    // 应用新的语言
    applyLanguage(lang);
}

// 页面加载时，从 URL 或 localStorage 读取语言
document.addEventListener("DOMContentLoaded", function () {
    const urlLang = getLanguageFromURL();
    applyLanguage(urlLang);

    // 设置语言选择框的默认值
    document.getElementById("languageSelector").value = urlLang;
});
